apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    k8s-addon: ingress-nginx.addons.k8s.io
    app: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      k8s-addon: ingress-nginx.addons.k8s.io
  maxUnavailable: {{ .Values.maxUnavailable }}
